---
include:
  - project: "Bigouden/gitlab-ci-templates"
    file: ".gitlab-ci-docker.yml"

.services:
  services:
    - name: $CONTAINER_TEST_IMAGE
      alias: docker-http-sd
  image: $CONTAINER_CLIENT_IMAGE
  before_script:
    - apk add --no-cache --update curl
  variables:
    GIT_STRATEGY: none
  dependencies: []

variables:
  DOCKER_HTTP_SD_PORT: "9999"
  DOCKER_HTTP_SD_SCHEME: "http"

stages:
  - Quality
  - Security
  - Build
  - Test
  - Inspect
  - Release
  - Clean

Docker HTTP Service Discovery:
  stage: Test
  extends: .services
  script:
    - curl -f --connect-timeout 60 ${DOCKER_HTTP_SD_SCHEME}://docker-http-sd:${DOCKER_HTTP_SD_PORT}
